# Installs (or removes) the no-admin Startup-folder autostart for ALFRED -
# the fallback for Install-AlfredAutostart.ps1 when Task Scheduler registration
# is blocked by "Access is denied" (common on non-elevated sessions).
#
# Generates AlfredBrain-Startup.vbs with THIS script's own location baked in
# (via $PSScriptRoot), so it works no matter where the repo is cloned - then
# copies it into shell:startup so it runs hidden at every logon. No admin
# rights required.
#
# Install:   powershell -ExecutionPolicy Bypass -File Install-AlfredStartup.ps1
# Uninstall: powershell -ExecutionPolicy Bypass -File Install-AlfredStartup.ps1 -Uninstall

param(
    [switch]$Uninstall
)

# --- Configuration ---
$brainDir = $PSScriptRoot
$startupDir = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
$startupVbs = Join-Path $startupDir 'AlfredBrain.vbs'
$oldStartupVbs = Join-Path $startupDir 'JarvisBrain.vbs'
$repoVbs = Join-Path $brainDir 'AlfredBrain-Startup.vbs'

if ($Uninstall) {
    if (Test-Path $startupVbs) {
        Remove-Item $startupVbs -Force
        Write-Host "Removed $startupVbs" -ForegroundColor Green
    } else {
        Write-Host "No installed copy found at $startupVbs - nothing to remove." -ForegroundColor Yellow
    }
    if (Test-Path $oldStartupVbs) {
        Remove-Item $oldStartupVbs -Force
        Write-Host "Also removed the legacy $oldStartupVbs" -ForegroundColor Green
    }
    Write-Host "If an ALFRED server is currently running, stop it manually (netstat -ano | findstr :7777)." -ForegroundColor Yellow
    exit 0
}

# --- Resolve node.exe ---
$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
    Write-Host "node.exe not found on PATH - install Node.js first." -ForegroundColor Red
    exit 1
}
$nodePath = $nodeCmd.Source

if (-not (Test-Path (Join-Path $brainDir 'server.mjs'))) {
    Write-Host "server.mjs not found in $brainDir - run this script from the brain folder." -ForegroundColor Red
    exit 1
}

# --- Generate the launcher with this machine's paths baked in ---
$vbsContent = @"
' AlfredBrain -- hidden autostart launcher (no-admin alternative to the scheduled task).
' Generated by Install-AlfredStartup.ps1 -- re-run that script if the repo moves.
' A copy of this file lives in shell:startup so the Alfred server comes up at every logon.
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "$brainDir"
WshShell.Run """$nodePath"" server.mjs", 0, False
"@

Set-Content -Path $repoVbs -Value $vbsContent -Encoding ASCII

New-Item -ItemType Directory -Force -Path $startupDir | Out-Null
Copy-Item -Path $repoVbs -Destination $startupVbs -Force

# Remove the old pre-rebrand launcher so it can't double-start the server.
if (Test-Path $oldStartupVbs) {
    Remove-Item $oldStartupVbs -Force
    Write-Host "Removed legacy launcher: $oldStartupVbs" -ForegroundColor Yellow
}

Write-Host "Startup-folder autostart installed (no admin required)." -ForegroundColor Green
Write-Host "  Repo copy:    $repoVbs" -ForegroundColor Green
Write-Host "  Startup copy: $startupVbs" -ForegroundColor Green
Write-Host "  Runs:         $nodePath server.mjs" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  - It will start automatically at your next logon." -ForegroundColor Cyan
Write-Host "  - To start it right now:  wscript.exe `"$startupVbs`"" -ForegroundColor Cyan
Write-Host "  - Then open http://localhost:7777 (or your PORT env var, if set)." -ForegroundColor Cyan
Write-Host "  - To remove:  powershell -ExecutionPolicy Bypass -File Install-AlfredStartup.ps1 -Uninstall" -ForegroundColor Cyan
