' AlfredBrain -- hidden autostart launcher (no-admin alternative to the scheduled task).
' Generated by Install-AlfredStartup.ps1 -- re-run that script if the repo moves.
' A copy of this file lives in shell:startup so the vault-brain server comes up at every logon.
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "C:\Users\dishi\OneDrive\Desktop\_Projects\Alfred\jarvis"
WshShell.Run """C:\Program Files\nodejs\node.exe"" server.mjs", 0, False
